#!/usr/bin/env bash

CHANGELOG_FILE=$1
NEW_VERSION="$2"
DATE=`date +'%Y-%m-%d'`
HEAD="\nVersion $NEW_VERSION \n"
SUBHEAD="Released on $DATE"

# create a separator, the same number of lines as the label above..
LEN=${#SUBHEAD}
CH='-'
SEP=`printf '%*s' "$LEN" ' ' | tr ' ' "$CH"`

case "$1" in
  -l|--list)
    version=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1))
    if test -z "$version"; then
      git log --pretty="format:  * %s"
    else
      git log --pretty="format:  * %s" $version..
    fi
    ;;
  *)
    # get default changelog file..
    if test "$CHANGELOG_FILE" = ""; then
      CHANGELOG_FILE=`ls | egrep 'change|history' -i`
      if test "$CHANGELOG_FILE" = ""; then CHANGELOG_FILE='HISTORY.md'; fi
    fi
    tmp="/tmp/changelog"
    printf "$HEAD$SEP \n\n$SUBHEAD \n\n" > $tmp
    git-changelog --list >> $tmp
    printf '\n\n' >> $tmp
    if [ -f $CHANGELOG_FILE ]; then cat $CHANGELOG_FILE >> $tmp; fi
    mv $tmp $CHANGELOG_FILE
    cat $CHANGELOG_FILE
    ;;
esac
